dataset_path: data/imdb_pt_subset.csv
results_log_path: logs/final_results.csv

models:
  - maritalk
  - deepseek-r1:7b
  - gemma:2b

strategies:
  - zero-shot
  - few-shot
  - cot

top_k: 3
num_epochs: 10

ollama_server_url: http://localhost:11434/api/chat

