dataset_path: data/imdb_pt_subset.csv
results_log_path: logs/final_results.csv

top_k: 10
multiobjective: true
max_generations: 10
population_size: 10

ollama_server_url: http://localhost:11434/api/chat 

evaluators:
  - name: gemma:2b
    tipo: ollama
    endpoint: http://localhost:11434/api/generate
    linguagem: pt
    role: evaluator

  - name: deepseek-r1:7b
    tipo: ollama
    endpoint: http://localhost:11434/api/generate
    linguagem: pt
    role: evaluator

  - name: sabiazinho-3
    tipo: maritalk
    endpoint: ${sabia_url}
    chave_api: ${sabia_api_key}
    role: evaluator

generator:
  name: gpt-4o-mini
  tipo: openai
  endpoint: ${openai_api_base}
  chave_api: ${openai_api_key}
  role: generator
  template_generator:
    system: |
      Você é um otimizador de prompts para classificação de sentimentos (positivo ou negativo).
      Seu papel é melhorar instruções para modelos de linguagem, gerando prompts curtos, diretos e eficazes.
      Gere apenas o prompt, sem explicações ou comentários adicionais:

    user_crossover: |
      Prompt A: "{prompt_a}"
      Prompt B: "{prompt_b}"
      Combine os dois prompts mantendo clareza e coerência.

    user_mutation: |
      Gere uma variação desse prompt mantendo o objetivo de classificar sentimentos com precisão:"{prompt}"

strategies:
  - name: zero-shot
    template: |
      {prompt_instruction}

      Texto: "{text}"

  - name: few-shot
    examples: |
      Texto: "Esta versão de Anna Christie está em alemão. Greta Garbo interpreta Anna Christie, mas todos os outros personagens têm atores diferentes da versão em inglês. Ambos foram filmados para trás porque Garbo teve um número de seguidores na Alemanha. É uma boa história e um imperdível para os fãs de Garbo."
      Classificação: positivo
      Texto: "Não é apenas um filme mal feito com baixo orçamento, mas a trama em si é apenas estúpida !!! Um homem místico que come mulheres?(E pela aparência, não virgem) ridículo !!!Se você não tem nada melhor para fazer (como dormir), deve assistir isso. Okay, certo."
      Classificação: negativo

    template: |
      {prompt_instruction}

      {examples}
      Texto: "{text}"

  - name: cot
    template: |
      {prompt_instruction}

      Texto: "{text}"

      Explicação: Analise o sentimento do seguinte texto. Primeiro explique por que é positivo ou negativo, depois informe a classificação final. Responda apenas positivo ou negativo.